spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-worker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

notification:
  kafka:
    topics:
      request-queued: notification.request.queued.v1

logging:
  level:
    root: info
