spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

notification:
  kafka:
    topics:
      request-queued: notification.request.queued.v1
    monitor:
      worker-group-id: notification-worker

logging:
  level:
    org.hibernate.SQL: debug
